name: Update README with Latest Projects

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install @octokit/rest
        
    - name: Update README with latest projects
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { Octokit } = require('@octokit/rest');
          const fs = require('fs');
          
          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN
          });
          
          // Get user's repositories, sorted by last updated
          const { data: repos } = await octokit.rest.repos.listForUser({
            username: '0xb0rn3',
            sort: 'updated',
            direction: 'desc',
            per_page: 10
          });
          
          // Filter out forks and get top 3 original repos
          const latestRepos = repos
            .filter(repo => !repo.fork && !repo.name.includes('0xb0rn3'))
            .slice(0, 3);
          
          // Generate the project cards HTML
          let projectsHtml = '<div align="center">\n\n### Recent Activity\n\n<table>\n<tr>\n';
          
          for (let i = 0; i < Math.min(latestRepos.length, 3); i++) {
            const repo = latestRepos[i];
            projectsHtml += `<td align="center">
<a href="${repo.html_url}">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=0xb0rn3&repo=${repo.name}&theme=tokyonight&hide_border=true&bg_color=0D1117&title_color=6C7B95&text_color=8B949E" alt="${repo.name}"/>
</a>
</td>`;
            
            if (i === 1) projectsHtml += '\n</tr>\n<tr>\n';
          }
          
          projectsHtml += '\n</tr>\n<tr>\n';
          
          // Add commit status badges
          for (let i = 0; i < Math.min(latestRepos.length, 3); i++) {
            const repo = latestRepos[i];
            projectsHtml += `<td align="center">
<img src="https://img.shields.io/github/last-commit/0xb0rn3/${repo.name}?style=flat-square&color=6C7B95&bg_color=0D1117" alt="Last Commit"/>
</td>`;
          }
          
          projectsHtml += '\n</tr>\n</table>\n\n</div>';
          
          // Read current README
          let readme = fs.readFileSync('README.md', 'utf8');
          
          // Replace the projects section
          const startMarker = '<!-- LATEST-PROJECTS-START -->';
          const endMarker = '<!-- LATEST-PROJECTS-END -->';
          
          const startIndex = readme.indexOf(startMarker);
          const endIndex = readme.indexOf(endMarker);
          
          if (startIndex !== -1 && endIndex !== -1) {
            const before = readme.substring(0, startIndex + startMarker.length);
            const after = readme.substring(endIndex);
            
            readme = before + '\n' + projectsHtml + '\n' + after;
            
            fs.writeFileSync('README.md', readme);
          }
          
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Update README with latest projects"
        git push
